# # version: '3.8'

# services:
#   web:
#     build: .
#     entrypoint: ["/code/entrypoint.sh"]
#     volumes:
#       - .:/code
#       - static_volume:/code/staticfiles
#     ports:
#       - "8000:8000"
#     restart: unless-stopped
#     env_file:
#       - django_secret_key
#     environment:
#       - DJANGO_STATICFILES_STORAGE=django.contrib.staticfiles.storage.ManifestStaticFilesStorage

# volumes:
#   static_volume:

# version: '3.8'


services:
  web:
    build:
      context: .
      args:
        GIT_REPO: ${GIT_REPO:-https://github.com/anandarupmukherjee/InventoryManagementModular.git}
        GIT_REF: ${GIT_REF:-main}
    command: |
      bash -c "
        set -e
        python manage.py migrate
        mkdir -p staticfiles
        printf '%s\n' '{"paths": {}, "version": "1.0"}' > staticfiles/staticfiles.json
        python manage.py collectstatic --noinput --verbosity 2
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - static_volume:/code/stock_control/staticfiles
    expose:
      - "8000"               # Use 'expose' instead of 'ports' since only nginx needs to access it
    restart: unless-stopped
    env_file:
      - django_secret_key
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"               # This maps port 80 of host to container
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/code/stock_control/staticfiles:ro
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:

volumes:
  static_volume:
