# Generated by Django 4.2.11 on 2025-05-01 20:50

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('supplier', models.CharField(choices=[('LEICA', 'Leica'), ('THIRD_PARTY', 'Third Party')], default='LEICA', max_length=20)),
                ('threshold', models.PositiveIntegerField()),
                ('lead_time', models.DurationField(default=datetime.timedelta(days=1), help_text='Lead time (e.g., 1 day, 2 hours)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(default='LOT000', max_length=50)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock available for this lot', max_digits=12)),
                ('units_per_quantity', models.PositiveIntegerField(default=1)),
                ('accumulated_partial', models.PositiveIntegerField(default=0)),
                ('product_feature', models.CharField(choices=[('unit', 'Unit'), ('volume', 'Volume')], default='unit', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data_storage.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Ordered', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('product_code', models.CharField(default='N/A', max_length=50)),
                ('product_name', models.CharField(default='Unnamed Product', max_length=100)),
                ('lot_number', models.CharField(default='UNKNOWN', max_length=50)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='For unit-based: store integer (e.g., 1.00); for volume-based: store decimal (e.g., 0.5)', max_digits=12)),
                ('withdrawal_type', models.CharField(choices=[('unit', 'Full Item'), ('volume', 'Volume'), ('part', 'Partial Withdrawal')], default='unit', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('parts_withdrawn', models.PositiveIntegerField(blank=True, default=0, help_text='Number of partial units withdrawn, if not a full item')),
                ('product_code', models.CharField(default='N/A', max_length=50)),
                ('product_name', models.CharField(default='Unnamed Product', max_length=100)),
                ('lot_number', models.CharField(default='UNKNOWN', max_length=50)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.productitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderCompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_completions_completed', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_completions_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_logs', to='data_storage.purchaseorder')),
            ],
        ),
    ]
