# Generated by Django 5.2.1 on 2025-09-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotAcceptanceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('signed_off_by', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('test_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests', to='data_storage.productitem')),
            ],
            options={
                'indexes': [models.Index(fields=['product_item', 'created_at'], name='data_storag_product_07c6a0_idx'), models.Index(fields=['product_item', 'passed'], name='data_storag_product_39e9ca_idx')],
            },
        ),
    ]
