# Generated by Django 5.2.1 on 2025-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0002_lotacceptancetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
