# Generated by Django 5.2.1 on 2025-09-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0004_location_productitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='data_storage.location'),
        ),
    ]
