# Generated by Django 5.2.1 on 2025-09-16 14:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0005_withdrawal_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity registered from this scan', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('product_code', models.CharField(default='N/A', max_length=50)),
                ('product_name', models.CharField(default='Unnamed Product', max_length=100)),
                ('lot_number', models.CharField(default='UNKNOWN', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_registrations', to='data_storage.location')),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_storage.productitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
