enabled_modules:
  - enable_analysis
  - enable_reporting
  - enable_user_interface
  - enable_stock_admin
  - enable_data_collection
  - enable_data_collection_2
  - enable_data_collection_3
  - enable_data_collection_4
